### ISSUE TITLE
Enhance Live Link Error Message Styling

### ISSUE THREAD

**Issue by JohnPatrickAncajas** [MrAshwin2142/The-Wall-of-Projects#22]
**Issue Description:**

I suggest improving the styling of the live link error message to make it more visually appealing and user-friendly.

**Current Styling:**

The current styling of the live link error message is functional but lacks visual appeal. It uses a basic color scheme and minimal formatting.

**Enhancement Details:**

- Adjust the position of the error message to ensure it is consistently displayed in a user-friendly and intuitive location.

- Refine the layout to maintain consistency with the overall design of the application.

- Optimize spacing and alignment for better visual coherence with the rest of the user interface.

**Additional Context:**

The project uses HTML and CSS for rendering error messages. The goal is to make the error message stand out and provide a clear indication of the issue.

**Comment by MrAshwin2142** [comment]
Screenshot for reference. 
![Screenshot 2023-11-08 184257](https://github.com/MrAshwin2142/The-Wall-of-Projects/assets/89156541/f0c782c3-dc20-4730-9948-7f03f3890842)

**Comment by IrfanSalim** [comment]
Hey, I would like to work on this

**Comment by Shoyebaktar-shirol** [comment]
Hey, @MrAshwin2142  please assign me this issue definitely I will try to create user friendly interface.

**Comment by MrAshwin2142** [comment]
hey @Shoyebaktar-shirol and @IrfanSalim ,
could you please provide a brief overview of the changes you plan to make?This will help ensure coordination and avoid any duplication of efforts. Thank you for your contribution! 😊

We'll assign the issue to both of you now. Your combined efforts will help enhance the user experience. 🌟

**Comment by Shoyebaktar-shirol** [comment]
Okey thank you @MrAshwin2142  for assigning us this issue.

**Comment by MrAshwin2142** [comment]
I think we are done with issue,thank you @IrfanSalim and @Shoyebaktar-shirol for you contribution.
