### ISSUE TITLE
Implement Sorting for Star Contributors by Projects Added

### ISSUE THREAD

**Issue by MrAshwin2142** [MrAshwin2142/The-Wall-of-Projects#30]
#### Problem
Our star contributors table lacks sorting, making it challenging to identify top contributors easily.

#### Before Sorting
Here is a snapshot of our star contributors table in its current state, without the sorting feature. As you can see, the contributors are listed without any particular order, making it challenging to quickly identify those who have contributed the most projects.

![unsorted_star_sontributors_table](https://github.com/MrAshwin2142/The-Wall-of-Projects/assets/89156541/f68eea85-6693-467e-ad7f-f48fda21097a)

#### Proposed Solution
Implement sorting based on the number of projects added by each contributor.

**Comment by IrfanSalim** [comment]
Hey, I would like to take this up

**Comment by MrAshwin2142** [comment]
Thank you @IrfanSalim ! Go ahead, and feel free to reach out if you need any assistance.
