### ISSUE TITLE
Add Active Class to Project Buttons

### ISSUE THREAD

**Issue by MrAshwin2142** [MrAshwin2142/The-Wall-of-Projects#32]
#### Problem

Currently, project buttons don't visually indicate when they are active or clicked.

#### Proposed Solution

We should add an active class to project buttons when they are clicked to provide users with visual feedback.

#### Expected Outcome

With the active class added users will have a clearer indication of which project button is currently selected, improving the overall user experience.

**Comment by laibatariq07** [comment]
I am new to open source contribution. I want to work on this. 
I will change the background color of the buttons when they are clicked.

**Comment by MrAshwin2142** [comment]
Welcome, @laibatariq07 ! Changing the background color of the buttons when clicked sounds like a fantastic addition. Feel free to go ahead, and if you have any questions or need assistance, don't hesitate to ask. Happy coding!

**Comment by laibatariq07** [comment]
In the 2nd last commit of PR #33, titled "Update script.js," there seems to be an error. The modification replacing the if statement with an else-if statement is causing an issue where the "active" class fails to apply in certain scenarios. I've attached a screenshot for your reference, highlighting the problem.

![Capture](https://github.com/MrAshwin2142/The-Wall-of-Projects/assets/89126735/321c60f5-3561-4193-9912-aee8c95542dc)

**Comment by MrAshwin2142** [comment]
Thank you for addressing this issue.

**Comment by MrAshwin2142** [comment]
hey @laibatariq07 I have removed "else" but still it is not working in some cases can you look into it ..

**Comment by laibatariq07** [comment]
Yes sure

**Comment by laibatariq07** [comment]
Here is the modified code. Now It will work on all cases. Please check the code and guide me for further improvements.

projectButton.addEventListener("click", () => {
      if(currentClickedButton){
        currentClickedButton.classList.remove("active");
      }

      if(currentClickedButton !== projectButton){
        projectButton.classList.add("active");
        currentClickedButton = projectButton;
      } else{
        currentClickedButton = null;
      }

      displayProjectDetails(project, elements);
    });

**Comment by MrAshwin2142** [comment]
Your code looks good; it appears to cover all cases,
