### ISSUE TITLE
Redesigned Project Display Buttons

### ISSUE THREAD

**Issue by MrAshwin2142** [MrAshwin2142/The-Wall-of-Projects#37]
Hello, amazing contributors!
@JohnPatrickAncajas 
@IrfanSalim 
@KubasuIvanSakwa 
@Shoyebaktar-shirol 
@animasoul 
@laibatariq07 
@ktriggsdev 
@rishabh-patil-03 
@traez 
@globalnebula 
@SusheelThapa 

We're excited to share some recent design changes with you. We've revamped the project display to enhance clarity and user experience.

### Key Changes

1. **Project Image**: We've replaced the project button with a project image for a more visually appealing presentation.

2. **Used Technologies**: We've added a "Used Technologies" section to provide insights into the technologies or programming languages used in each project.

![Screenshot 2023-11-13 184249](https://github.com/MrAshwin2142/The-Wall-of-Projects/assets/89156541/15e72131-2a00-4046-a529-e58d5ba04391)

### Seeking Your Input
As valued contributors, we'd love to hear your thoughts and ideas on these design changes. Do you have any suggestions for further improvements? Is there anything else you'd like to see?

Feel free to share your feedback, and let's work together to make The Wall of Projects even better! Your insights are incredibly valuable, and we appreciate your contributions.

Happy coding, and thanks for being a part of this project!

**Comment by ktriggsdev** [comment]
Nice to see there have been further developments on this project, I was thinking though that the UI could be a bit more modernised, for example maybe use technologies like bootstrap to further enhance the style of the page if it is not already used. additionally the latest trend in css styles is something called neumorphism, which may be an interesting addition to the project. you can find that here: [https://neumorphism.io/](https://neumorphism.io/)

**Comment by Ademola111** [comment]
This is a welcome development and I am glad to see this coming to live. I would like to know if this changes have proceeded to development or still on decision stage. if available and not yet handled I would love to work on it and also implement bootstrap in it display for good user experience.

**Comment by arvind9140** [comment]
@MrAshwin2142  Can i take this issue
