### ISSUE TITLE
Improved Footer layout and design!

### ISSUE THREAD

**Issue by JohnPatrickAncajas** [MrAshwin2142/The-Wall-of-Projects#41]
Adjust the CSS styling of the footer section so it reaches the edges of the screen. Additional styling for improved design will also be much appreciated!

Current state:
![Screenshot (158)](https://github.com/MrAshwin2142/The-Wall-of-Projects/assets/143093214/a5aae664-1412-4890-8c61-7d984c252c1c)

**Comment by Muditakhatri** [comment]
can i get assigned?

**Comment by JohnPatrickAncajas** [comment]
Of course, sir @Muditakhatri! We appreciate your willingness to contribute.
