### ISSUE TITLE
Adjust Font Color

### ISSUE THREAD

**Issue by JohnPatrickAncajas** [MrAshwin2142/The-Wall-of-Projects#42]
Adjust the font-color of the 'ADD NEW PROJECT' button to improve its visibility on normal, hover, focus and active state.

Current state:
![Screenshot (161)](https://github.com/MrAshwin2142/The-Wall-of-Projects/assets/143093214/aa95428e-a4a2-48e6-820e-d083403eed04)

**Comment by mnajibi** [comment]
Hi there! I noticed the issue about adjusting the font color for better visibility, and I would like to help. May I take on this issue?

**Comment by Ademola111** [comment]
I think this have been solved. I noticed this when I clone the repo and try to preview it.

**Comment by JohnPatrickAncajas** [comment]
We appreciate the willingness to help but the task have been finished by someone already. Thank you!
