### ISSUE TITLE
Button Color Not Reverting to Normal After Closure

### ISSUE THREAD

**Issue by JohnPatrickAncajas** [MrAshwin2142/The-Wall-of-Projects#52]
The current issue involves a problem where, upon closing, the button color fails to revert to its original state. Adjust the code to make the button return to its inactive color when the element closes.

Current state:
![Screenshot (168)](https://github.com/MrAshwin2142/The-Wall-of-Projects/assets/143093214/9c216cb7-9440-4614-9e9f-c2e3b10b3001)

**Comment by animasoul** [comment]
Hi,
I can take this bug :)

**Comment by JohnPatrickAncajas** [comment]
Yes sir!
