### ISSUE TITLE
Improve Button UI - Color/Background Color

### ISSUE THREAD

**Issue by JohnPatrickAncajas** [MrAshwin2142/The-Wall-of-Projects#53]
The current button UI all share the same design at a certain state making it look like there are three active buttons at the same time. Improve the UI by changing this values to make their state more visible and understandable.

Current state:
![Screenshot (167)](https://github.com/MrAshwin2142/The-Wall-of-Projects/assets/143093214/1e236aba-3350-471b-a884-0df377510a14)

**Comment by mnajibi** [comment]
Hi, Can I work on this issue?

**Comment by JohnPatrickAncajas** [comment]
Yes ma'am @mnajibi! We appreciate the hep you offer.

**Comment by arvind9140** [comment]
@JohnPatrickAncajas can i solve this issue

**Comment by MrAshwin2142** [comment]
@arvind9140 Sure ..

**Comment by JohnPatrickAncajas** [comment]
This issue have been solved already! Sorry for the late update, school work is currently beating me up badly.
