### ISSUE TITLE
Feature Request: Display Total Number of Projects

### ISSUE THREAD

**Issue by MrAshwin2142** [MrAshwin2142/The-Wall-of-Projects#61]
Display total project count. Enhance user experience by showing the total number of projects on the web page.

**Comment by Ashwin1902** [comment]
Hi, I would like to work on this issue.

**Comment by MrAshwin2142** [comment]
Welcome @Ashwin1902 , I appreciate your willingness to contribute.

**Comment by Ashwin1902** [comment]
I have created a PR. Please review and provide feedback.

**Comment by MrAshwin2142** [comment]
Thanks, @Ashwin1902 ! feature added . Appreciate your help!
