### ISSUE TITLE
Enhancing Navbar and Homepage Styling

### ISSUE THREAD

**Issue by MrAshwin2142** [MrAshwin2142/The-Wall-of-Projects#76]
The current styling of the navbar and homepage lacks consistency and visual appeal in our project. This issue aims to improve the design and layout of the navbar and homepage to enhance user experience and create a more polished look for our application.

**Goals:**

1. Refine the design of the navbar to ensure it is responsive, intuitive, and visually appealing across different devices and screen sizes.
2. Enhance the homepage layout and styling to create a more engaging and professional appearance.
3. Ensure consistency in colors, fonts, and overall styling throughout the navbar and homepage sections.

**Comment by Halzorg** [comment]
Hi, I would like to work on this issue, could you please assign it to me?

**Comment by MacAhetti** [comment]
can i work on this?

**Comment by MacAhetti** [comment]
i have made a pull request for this issue can you check it out

**Comment by MacAhetti** [comment]
can you tell me what change do you need in navbar breifly?

**Comment by MrAshwin2142** [comment]
I have attached a screenshot for your reference. align all nav items on right side.

![Screenshot 2023-11-28 201640](https://github.com/MrAshwin2142/The-Wall-of-Projects/assets/89156541/df7f6893-79bb-4d71-8241-0a29c77fca0c)

**Comment by sahil-1729** [comment]
Is the issue solved? or is it open?

**Comment by MrAshwin2142** [comment]
> Is the issue solved? or is it open?

you can work on it .. if you have any idea to make it more intreactive .

**Comment by suvashish26** [comment]
I would like to work on it. Is the issue still open?
