### ISSUE TITLE
Dark Mode feature

### ISSUE THREAD

**Issue by Victorthedev** [MrAshwin2142/The-Wall-of-Projects#80]
The dark mode feature is pretty much common in modern websites and this is no different.
Adding it to the website would increase positive user experience and would consider users who may have photosensitive eyesight.

This feature should be optional, users should be able to click/toggle a button
it should take into consideration the current styling and modify it for dark mode.

**Comment by lucasfirmo62** [comment]
Hi @MrAshwin2142, I'm interested in making this issue, could you give me more information about what I should do?
