### ISSUE TITLE
 Enhancement Request: Improve Appearance of "ADD NEW PROJECT" Button.

### ISSUE THREAD

**Issue by Shoyebaktar-shirol** [MrAshwin2142/The-Wall-of-Projects#88]
hello @MrAshwin2142 , The "ADD NEW PROJECT" button looks too much like the other project buttons, making it hard to distinguish.

Preview :
![WhatsApp Image 2023-12-03 at 20 20 23_6903527e](https://github.com/MrAshwin2142/The-Wall-of-Projects/assets/113618917/fe230070-1461-49d7-869e-57aabbf9b973)

**Comment by chasepg0821** [comment]
@MrAshwin2142 Hi! I opened a PR that resolves this by duplicating the table header color for color scheme consistency while still making a clear distinction.

**Comment by MrAshwin2142** [comment]
Resolved by @chasepg0821
